version: 0.2.1-{build}

image: Visual Studio 2017

shallow_clone: true
clone_depth: 1

environment:
  matrix:
  - name: x86-64-VS
    qt: C:\Qt\5.9.2\msvc2017_64
    toolchain: MSVC2017-x86_x64
    installpath: .\release\install-root\
    artifactname: QtSemanticNotes-%APPVEYOR_BUILD_VERSION%-%name%

configuration: Release

init:
  - set PATH=%PATH%;%QT%\bin;C:\Qt\Tools\QtCreator\bin;
  - set VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC

before_build:
  - qbs setup-toolchains --detect
  - qbs setup-qt %qt%\bin\qmake.exe qt
  - qbs config profiles.qt.baseProfile %toolchain%

build_script:
  - qbs build profile:qt release qbs.installDir:%artifactname%

after_build:
  - qbs install profile:qt release qbs.installDir:%artifactname%
  - windeployqt --release --no-opengl-sw --no-system-d3d-compiler --no-translations --list relative %installpath%\%artifactname%
  - 7z a -tzip %artifactname%.zip %installpath%\%artifactname%

artifacts:
  - path: "%artifactname%.zip"
    name: "%artifactname%"
    type: zip

branches:
  only:
    - master
    - /v\d\.\d\.\d/

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: 1QXcIVsmMpHzP0dugtVCQ5LeAKVLIkAo4HHDf28FD4y91XcAzCke9HqDpvLgzuy5
  artifact: "%artifactname%"
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true
