version: 0.2.2-{build}

image: Visual Studio 2017

shallow_clone: true
clone_depth: 1

environment:
  matrix:
  - name: Win64
    qt: C:\Qt\5.9.2\msvc2017_64
    toolchain: MSVC2017-x86_x64
    installpath: .\release\install-root\
    artifactname: QtSemanticNotes-%APPVEYOR_BUILD_VERSION%-%name%
    installername: QtSemanticNotesInstaller-%APPVEYOR_BUILD_VERSION%-%name%

configuration: Release

init:
  - set PATH=%PATH%;%QT%\bin;C:\Qt\Tools\QtCreator\bin;C:\Qt\Tools\QtInstallerFramework\3.0\bin;
  - set VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC

before_build:
  - qbs setup-toolchains --detect
  - qbs setup-qt %qt%\bin\qmake.exe qt
  - qbs config profiles.qt.baseProfile %toolchain%

build_script:
  - qbs build profile:qt release qbs.installDir:%artifactname%

after_build:
  - qbs install profile:qt release qbs.installDir:%artifactname%
  - windeployqt --release --no-opengl-sw --no-system-d3d-compiler --no-translations %installpath%\%artifactname%
  - 7z a -tzip %artifactname%.zip %installpath%\%artifactname%
  - xcopy %installpath%\%artifactname%\vcredist* installer\packages\com.microsoft.vcredist\data\ /e /i
  - del %installpath%\%artifactname%\vcredist*
  - xcopy %installpath%\%artifactname%\* installer\packages\github.youkaicat.qtsemanticnotes\data\ /e /i
  - xcopy resources\icon.ico installer\packages\github.youkaicat.qtsemanticnotes\data\resources\ /e /i
  - binarycreator --offline-only -c installer\config\config.xml -p installer\packages %installername%

artifacts:
  - path: "%artifactname%.zip"
    name: "%artifactname%"
    type: zip
  - path: "%installername%.exe"
    name: "%installername%"
    type: zip

branches:
  only:
    - master
    - /v\d\.\d\.\d/

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: 1QXcIVsmMpHzP0dugtVCQ5LeAKVLIkAo4HHDf28FD4y91XcAzCke9HqDpvLgzuy5
  artifact: /QtSemanticNotes.*/
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true
