version: 0.2.1.{build}

image: Visual Studio 2017

shallow_clone: true
clone_depth: 1

environment:
  matrix:
  - name: x86-64-VS
    qt: C:\Qt\5.9.2\msvc2017_64
    toolchain: MSVC2017-x86_x64
    targetpath: .\release\install-root\

configuration: Release

init:
  - set PATH=%PATH%;%QT%\bin;C:\Qt\Tools\QtCreator\bin;
  - set VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC

before_build:
  - qbs setup-toolchains --detect
  - qbs setup-qt %qt%\bin\qmake.exe qt
  - qbs config profiles.qt.baseProfile %toolchain%

build_script:
  - qbs build profile:qt release
  - qbs install profile:qt release

after_build:
  - windeployqt --release --no-opengl-sw --no-system-d3d-compiler --no-translations --list relative %targetpath%
  - 7z a QtSemanticNotes-%APPVEYOR_BUILD_VERSION%-%name%.zip %targetpath%

artifacts:
  - path: QtSemanticNotes-%APPVEYOR_BUILD_VERSION%-%name%.zip
    name: QtSemanticNotes-%APPVEYOR_BUILD_VERSION%-%name%
    type: zip

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: f1qLXI72FZwkMS6SHE+dBvV4N9t3AZzUOpxexMXs2h79b3mVqTgZ/1Mw3x/L+rSj
  artifact: QtSemanticNotes-%APPVEYOR_BUILD_VERSION%-%name%
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
